// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zakjenxiwwukogfaxmiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpha2plbnhpd3d1a29nZmF4bWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NjY4NzQsImV4cCI6MjA2NDM0Mjg3NH0.WKa94fwEhrB2TJxA2OzLvBck-frPWmlhPkJ97CG6roQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);